<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="azpoc._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div>
        <br />
        <div style="width:whitesmoke;">
            <asp:Label ID="Label1" runat="server" Text="First Name: "></asp:Label><asp:TextBox ID="fname" runat="server"></asp:TextBox>
            <asp:Label ID="Label2" runat="server" Text="Last Name: "></asp:Label><asp:TextBox ID="lname" runat="server"></asp:TextBox>
            <asp:Label ID="Label3" runat="server" Text="City : "></asp:Label><asp:TextBox ID="city" runat="server"></asp:TextBox>
            <asp:Label ID="Label4" runat="server" Text="State: "></asp:Label><asp:TextBox ID="state" runat="server"></asp:TextBox>
        <br />   
            <asp:Button ID="submit" runat="server" Text="Submit" OnClick="submit_Click" />
            <asp:Button ID="clear" runat="server" Text="Clear" OnClick="clear_Click" />
        </div>
    <br />
    <asp:Label ID="Label7" runat="server" Text="Web Server: "></asp:Label>
    <asp:Label ID="webserver" runat="server" Text="N/A"></asp:Label>
    <br />
    <asp:Label ID="Label5" runat="server" Text="Read-Write DB Server: "></asp:Label>
    <asp:Label ID="connstr_rw" runat="server" Text="N/A"></asp:Label>
    <br />
    <asp:Label ID="Label6" runat="server" Text="Read DB Server: "></asp:Label>
    <asp:Label ID="connstr_r" runat="server" Text="N/A"></asp:Label>
    <br />
    <br />
    <asp:GridView ID="GridView1" runat="server" AutoGenerateEditButton="True" AutoGenerateColumns="False" DataKeyNames="Id" 
        OnSelectedIndexChanged="GridView1_SelectedIndexChanged" 
        onrowediting="GridView1_RowEditing" 
        OnRowUpdating="GridView1_RowUpdating"
        AutoGenerateDeleteButton="True">
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
            <asp:BoundField DataField="FirstName" HeaderText="First Name" SortExpression="FirstName" />
            <asp:BoundField DataField="LastName" HeaderText="Last Name" SortExpression="Last Name" />
            <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
            <asp:BoundField DataField="State" HeaderText="State" SortExpression="State" />
        </Columns>
    </asp:GridView>
        
        <asp:GridView ID="GridView2" runat="server">

        </asp:GridView>


    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:AZ-POCDbWrite %>" 
        UpdateCommand="UPDATE Employee SET FirstName = @FirstName, LastName = @LastName, City = @City , State = @State WHERE ID = @ID"
        DeleteCommand="DELETE FROM Employee WHERE ID = @ID"
        >
        <UpdateParameters>
            <asp:Parameter Name="ID" Type="String" />
            <asp:Parameter Name="FirstName" Type="String" />
            <asp:Parameter Name="LastName" Type="String" />
            <asp:Parameter Name="City" Type="String" />
            <asp:Parameter Name="State" Type="String" />
        </UpdateParameters> 
        <DeleteParameters>
            <asp:Parameter Name="ID" /> 
        </DeleteParameters>
    </asp:SqlDataSource>
    </div>
</asp:Content>
