<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="azpoc.Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div>
        <br />
        <div style="width:whitesmoke;">
            <div>
            <asp:Label ID="Label1" runat="server" Text="First Name: " Width="100"></asp:Label><asp:TextBox ID="fname" runat="server"></asp:TextBox>
                <br />
            <asp:Label ID="Label2" runat="server" Text="Last Name: " Width="100"></asp:Label><asp:TextBox ID="lname" runat="server"></asp:TextBox>
                <br />
            <asp:Label ID="Label3" runat="server" Text="City: " Width="100" ></asp:Label><asp:TextBox ID="city" runat="server"></asp:TextBox>
                <br />
            <asp:Label ID="Label4" runat="server" Text="State: " Width="100"></asp:Label><asp:TextBox ID="state" runat="server"></asp:TextBox>
            </div>
            <div>

            <asp:Button ID="submit" runat="server" Text="Submit" OnClick="submit_Click" Width="100" />
            <asp:Button ID="clear" runat="server" Text="Clear Input" OnClick="clear_Click" Width="100"/>
            <asp:Button ID="refresh" runat="server" Text="Refresh" OnClick="refresh_Click" Width="100" />

            </div>
        </div>
    <br />
    <asp:Label ID="Label7" runat="server" Text="Web Server: "></asp:Label>
    <asp:Label ID="webserver" runat="server" Text="N/A"></asp:Label>
    <br />
    <asp:Label ID="Label5" runat="server" Text="Read-Write DB Server: "></asp:Label>
    <asp:Label ID="connstr_rw" runat="server" Text="N/A"></asp:Label>
    <br />
    <asp:Label ID="Label6" runat="server" Text="Read DB Server: "></asp:Label>
    <asp:Label ID="connstr_r" runat="server" Text="N/A"></asp:Label>
    <br />
    <br />
    <asp:GridView ID="GridView1" runat="server" DataKeyNames="Id" 
        OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." 
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" EditRowStyle-BackColor="#66CCFF" Width="1000px" CellPadding="5" CellSpacing="1">
        <AlternatingRowStyle BackColor="#CCCCCC" />
<EditRowStyle BackColor="#66CCFF" Width="600px"></EditRowStyle>
        <HeaderStyle BorderStyle="Double" HorizontalAlign="Center" />
    </asp:GridView>
    </div>
</asp:Content>
